[build]
  command = "npm install --force && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"  # Using Node 18 instead of 22 for better compatibility
  
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"