import { PsychTerm } from './Learn';

// Additional concepts from the psychology cheat sheet
export const moreConcepts2: PsychTerm[] = [
  {
    term: "Actor-Observer Bias",
    story: "When Raj made a mistake at work, he blamed the tight deadline. When his colleague made the same mistake, Raj thought it was because she wasn't detail-oriented enough.",
    explanation: "Actor-observer bias is the tendency to attribute our own actions to external factors while attributing other people's behaviors to their personal characteristics.",
    category: "Social Perception",
    icon: "social",
  },
  {
    term: "Endowment Effect",
    story: "Nina refused a $50 offer for a concert ticket she purchased for $40, even though she couldn't attend. Simply owning the ticket made it more valuable to her.",
    explanation: "The endowment effect describes our tendency to value things more highly simply because we own them, regardless of their objective market value.",
    category: "Behavioral Economics",
    icon: "behavioral",
  },
  {
    term: "Optimism Bias",
    story: "Despite knowing the statistics about car accidents, Mark never wore his seatbelt, believing that bad things 'only happen to other people.'",
    explanation: "Optimism bias leads us to believe we're less likely to experience negative events and more likely to experience positive ones than is statistically likely.",
    category: "Self Perception",
    icon: "cognitive",
  },
  {
    term: "Bandwagon Effect",
    story: "Jacob had no interest in cryptocurrency until everyone in his office started investing. Feeling he might miss out, he invested a significant amount without doing any research.",
    explanation: "The bandwagon effect is the tendency to believe or do something because many other people believe or do the same, often driven by conformity and fear of missing out.",
    category: "Social Influence",
    icon: "social",
  },
  {
    term: "Just-World Hypothesis",
    story: "When hearing about someone's misfortune, Olivia often thinks, 'They must have done something to deserve that,' even when no evidence suggests this is true.",
    explanation: "The just-world hypothesis is the cognitive bias that assumes people get what they deserve - that good things happen to good people and bad things to bad people.",
    category: "Social Perception",
    icon: "cognitive",
  },
  {
    term: "Curse of Knowledge",
    story: "As an expert pianist, Dr. Lee couldn't understand why her beginner students struggled with 'simple' concepts that seemed obvious and intuitive to her.",
    explanation: "The curse of knowledge is a cognitive bias where better-informed people find it difficult to consider problems from the perspective of less-informed people.",
    category: "Cognitive Biases",
    icon: "cognitive",
  },
  {
    term: "Negativity Bias",
    story: "After receiving ten positive comments and one criticism on her presentation, Sophia obsessed over the single negative remark and dismissed all the praise.",
    explanation: "Negativity bias is our tendency to give more weight to negative experiences or information than positive ones, which affects our memory, attention, and decision-making.",
    category: "Cognitive Biases",
    icon: "cognitive",
  },
  {
    term: "Illusion of Control",
    story: "When playing slots, Vincent had a lucky ritual of tapping the machine three times before pulling the lever, believing it increased his chances of winning.",
    explanation: "The illusion of control is the tendency to believe we can influence outcomes that are actually determined by chance, particularly when we feel personally involved.",
    category: "Cognitive Biases",
    icon: "cognitive",
  },
  {
    term: "Reactive Devaluation",
    story: "When his rival company proposed a solution to a shared problem, CEO Thomas immediately dismissed it as flawed, despite it being nearly identical to one his own team had considered.",
    explanation: "Reactive devaluation is the tendency to devalue proposals or ideas that are perceived to originate from an antagonist or someone we view negatively.",
    category: "Decision Making",
    icon: "emotional",
  },
  {
    term: "Status Quo Bias",
    story: "Even though a new health insurance plan would save her money, Rita stayed with her current plan because the effort of changing seemed too overwhelming.",
    explanation: "Status quo bias is our tendency to prefer the current state of affairs, viewing any change from the baseline as a loss. We often stick with familiar options even when better alternatives exist.",
    category: "Decision Making",
    icon: "behavioral",
  },
  {
    term: "Bystander Effect",
    story: "When Alicia fell on the crowded street, many people walked by assuming someone else would help. It wasn't until someone directly asked 'Are you okay?' that assistance was offered.",
    explanation: "The bystander effect occurs when the presence of others discourages an individual from intervening in an emergency situation. The greater the number of bystanders, the less likely it is that any one of them will help.",
    category: "Social Influence",
    icon: "social",
  },
  {
    term: "Affect Heuristic",
    story: "Despite statistics showing flying is safer than driving, Gabe chose to drive 500 miles rather than fly because plane crashes on the news made flying seem terrifying.",
    explanation: "The affect heuristic is a mental shortcut where emotional responses influence decisions more than rational evaluation of risks and benefits.",
    category: "Decision Making",
    icon: "emotional",
  },
  {
    term: "Choice Overload",
    story: "When faced with choosing between 30 different vacation destinations, Jamie became overwhelmed and decided not to take a vacation at all.",
    explanation: "Choice overload occurs when having too many options decreases our satisfaction with our choice or leads to decision paralysis. More options can make decisions harder rather than better.",
    category: "Decision Making",
    icon: "cognitive",
  },
  {
    term: "Unit Bias",
    story: "At the restaurant, Theo finished his oversized portion even though he was full halfway through, thinking, 'I should finish the whole serving.'",
    explanation: "Unit bias is our tendency to prefer completing a full unit of something once we've started it. We view a single entity (like one plate of food) as the appropriate amount to consume.",
    category: "Behavioral Patterns",
    icon: "behavioral",
  },
  {
    term: "Stereotype Threat",
    story: "Before taking a math test, Leah was reminded that 'girls typically score lower than boys on this test.' Her performance suffered, despite her usually excelling at math.",
    explanation: "Stereotype threat occurs when awareness of negative stereotypes about one's social group creates performance anxiety, which can impair performance and inadvertently confirm the stereotype.",
    category: "Social Influence",
    icon: "social",
  },
  {
    term: "Authority Bias",
    story: "Despite his own medical knowledge, Dr. Jenkins accepted a questionable treatment plan for his mother without questioning it because it came from a renowned specialist.",
    explanation: "Authority bias is our tendency to trust and obey authority figures, often accepting their ideas and directives without sufficient questioning or scrutiny.",
    category: "Social Influence",
    icon: "social",
  },
  {
    term: "Naive Realism",
    story: "During a political discussion, Natalie couldn't understand how her friend could support the opposing candidate, thinking, 'My political views are based on facts, while hers are clearly biased.'",
    explanation: "Naive realism is the belief that we see the world objectively while others are influenced by bias. We assume that people who disagree with us are uninformed, irrational, or biased.",
    category: "Self Perception",
    icon: "cognitive",
  },
  {
    term: "Gambler's Fallacy",
    story: "After five coin flips resulting in heads, Juan was convinced the next flip would be tails. 'It has to balance out,' he thought, not realizing each flip is independent.",
    explanation: "The gambler's fallacy is the mistaken belief that random events are influenced by previous outcomes. If something happens more frequently than expected, we wrongly believe it will happen less frequently in the future.",
    category: "Cognitive Biases",
    icon: "cognitive",
  },
  {
    term: "Effort Justification",
    story: "After spending six months learning to play a difficult piece on the piano, Yuri claimed it was the most beautiful piece ever written, partly because he'd invested so much time in it.",
    explanation: "Effort justification is our tendency to value outcomes more when we've put significant effort into achieving them. We increase the perceived value to justify the effort expended.",
    category: "Behavioral Economics",
    icon: "behavioral",
  },
  {
    term: "Weber-Fechner Law",
    story: "When shopping, Rachel easily noticed the difference between a $10 and $20 shirt, but couldn't perceive much difference between a $1,010 and $1,020 furniture piece, despite the same $10 gap.",
    explanation: "The Weber-Fechner Law states that the just-noticeable difference between similar stimuli is proportional to the magnitude of the stimuli. Small differences in large quantities are harder to perceive than the same differences in small quantities.",
    category: "Perception",
    icon: "cognitive",
  }
];
