import { PsychTerm } from './Learn';

// Third batch of additional concepts from the psychology cheat sheet
export const moreConcepts3: PsychTerm[] = [
  {
    term: "Outcome Bias",
    story: "The company praised a manager who took a huge, unnecessary risk that happened to succeed, while criticizing another who made a sound decision that didn't work due to unpredictable circumstances.",
    explanation: "Outcome bias occurs when we judge a decision based on its outcome rather than the quality of the decision at the time it was made, ignoring the role of luck and circumstances.",
    category: "Decision Making",
    icon: "cognitive",
  },
  {
    term: "Group Polarization",
    story: "The book club members individually had moderate opinions about the novel, but after discussion, they collectively adopted an extremely negative view that was more critical than any individual's initial stance.",
    explanation: "Group polarization is the tendency for groups to make decisions that are more extreme than the initial inclinations of their members, as discussion strengthens pre-existing tendencies.",
    category: "Social Influence",
    icon: "social",
  },
  {
    term: "Survivorship Bias",
    story: "Inspired by stories of college dropouts who became tech billionaires, Ethan quit university to launch a startup, not considering the thousands of dropouts who failed at similar ventures.",
    explanation: "Survivorship bias is the logical error of focusing on people or things that 'survived' a selection process while overlooking those that did not, leading to overly optimistic beliefs.",
    category: "Cognitive Biases",
    icon: "cognitive",
  },
  {
    term: "Illusory Correlation",
    story: "After eating ice cream and experiencing headaches twice in one week, Patricia became convinced that dairy caused her headaches, ignoring the many times she consumed dairy without any issues.",
    explanation: "Illusory correlation is perceiving a relationship between variables when no such relationship exists, or the relationship is weaker than believed. It's often driven by confirmation bias and selective attention.",
    category: "Cognitive Biases",
    icon: "cognitive",
  },
  {
    term: "Focusing Effect",
    story: "When deciding between job offers, Diego overemphasized the salary difference and undervalued factors like commute time, work culture, and growth opportunities that would impact his daily happiness.",
    explanation: "The focusing effect is a cognitive bias that occurs when people place too much importance on one aspect of an event, causing an error in accurately predicting the utility of a future outcome.",
    category: "Decision Making",
    icon: "cognitive",
  },
  {
    term: "Functional Fixedness",
    story: "When Lydia's team needed to hang a poster but had no hammer, no one thought to use the heavy stapler as a substitute until a new intern suggested it.",
    explanation: "Functional fixedness is the cognitive bias that limits a person to use an object only in the way it is traditionally used, preventing creative problem-solving and innovation.",
    category: "Cognitive Processes",
    icon: "cognitive",
  },
  {
    term: "Misinformation Effect",
    story: "After witnessing a car accident, Harry's memory of a blue sedan changed to a blue SUV after other witnesses mentioned an SUV, even though they were mistaken.",
    explanation: "The misinformation effect occurs when post-event information interferes with the memory of the original event. Memory becomes less accurate because of exposure to misleading information.",
    category: "Memory",
    icon: "cognitive",
  },
  {
    term: "Default Effect",
    story: "When signing up for the company retirement plan, 89% of employees kept the default contribution rate of 3%, even though financial advisors recommended at least 6%.",
    explanation: "The default effect is our tendency to accept default options rather than choosing an alternative, even when the alternative would be better. It highlights the power of pre-selected options.",
    category: "Decision Making",
    icon: "behavioral",
  },
  {
    term: "Moral Licensing",
    story: "After donating to charity in the morning, Ben felt justified in later cutting in line at the coffee shop, thinking, 'I've already done something good today.'",
    explanation: "Moral licensing is the phenomenon where doing something good gives people a subconscious permission to do something less virtuous later, as if they've 'earned' moral credit.",
    category: "Behavioral Patterns",
    icon: "behavioral",
  },
  {
    term: "Pratfall Effect",
    story: "The audience found the flawless speaker impressive but distant, while they found the equally qualified speaker who spilled water and laughed it off more relatable and likeable.",
    explanation: "The pratfall effect is the tendency for people's attractiveness to increase after they commit a minor blunder. Small mistakes humanize competent individuals and make them more relatable.",
    category: "Social Perception",
    icon: "social",
  },
  {
    term: "False Consensus Effect",
    story: "When planning the office party, Hannah chose a karaoke theme, genuinely surprised when most colleagues expressed disappointment as she assumed everyone enjoyed singing as much as she did.",
    explanation: "The false consensus effect is our tendency to overestimate how much others agree with our opinions, beliefs, and habits. We assume others think like us more than they actually do.",
    category: "Social Perception",
    icon: "social",
  },
  {
    term: "Attentional Bias",
    story: "After learning she was pregnant, Vanessa suddenly noticed pregnant women everywhere, though the actual number hadn't changed—she just hadn't noticed them before.",
    explanation: "Attentional bias is the tendency to pay attention to certain stimuli while ignoring others. Things that are emotionally charged or relevant to our current goals receive disproportionate attention.",
    category: "Cognitive Processes",
    icon: "cognitive",
  },
  {
    term: "Positivity Offset",
    story: "Despite having no specific expectations, Aisha felt pleasantly excited about her blind date, demonstrating the mild optimism we often feel toward neutral situations.",
    explanation: "Positivity offset is our tendency to interpret neutral situations slightly positively. In the absence of threat, people typically maintain a mildly positive outlook.",
    category: "Emotional Patterns",
    icon: "emotional",
  },
  {
    term: "Humor Effect",
    story: "Six months after a training session, employees remembered the funny stories and examples far better than the serious technical information.",
    explanation: "The humor effect is the tendency for humorous information to be more easily remembered than non-humorous information. Humor creates stronger encoding and retrieval paths in memory.",
    category: "Memory",
    icon: "cognitive",
  },
  {
    term: "Spacing Effect",
    story: "Sam studied Spanish vocabulary for 15 minutes daily for a month and retained far more than his roommate who crammed for 7 hours the day before the test.",
    explanation: "The spacing effect demonstrates that learning is more effective when study sessions are spaced out over time, rather than crammed into a single session. Distributed practice leads to stronger memory formation.",
    category: "Learning",
    icon: "cognitive",
  },
  {
    term: "Identifiable Victim Effect",
    story: "The charity raised thousands for medical treatment for one child whose story and photo were featured, but much less for a program helping hundreds of anonymous children.",
    explanation: "The identifiable victim effect describes our tendency to respond more strongly to the suffering of a specific, identifiable individual than to a large, anonymous group facing the same problem.",
    category: "Emotional Responses",
    icon: "emotional",
  },
  {
    term: "Context Effect",
    story: "The real estate agent deliberately showed clients a run-down house first, making the moderately nice house they saw afterward seem much more appealing by comparison.",
    explanation: "The context effect describes how the surrounding environment influences perception and judgment. The same stimulus can be perceived differently depending on the context in which it appears.",
    category: "Perception",
    icon: "cognitive",
  },
  {
    term: "Dual-Process Theory",
    story: "While driving a familiar route, Chen was deep in thought about a work problem (System 2) while simultaneously navigating traffic and following road signs (System 1).",
    explanation: "Dual-process theory proposes that human thinking operates in two distinct systems: System 1 (fast, automatic, intuitive) and System 2 (slow, deliberate, analytical). These systems work together but handle different cognitive tasks.",
    category: "Cognitive Processes",
    icon: "cognitive",
  },
  {
    term: "Self-Regulation",
    story: "Though exhausted after work, Keisha stuck to her plan of going to the gym instead of collapsing on the couch, demonstrating her ability to override immediate desires for long-term goals.",
    explanation: "Self-regulation is the ability to monitor and control our own behavior, emotions, and thoughts, altering them according to the demands of the situation. It's central to pursuing goals and resisting impulses.",
    category: "Self Development",
    icon: "behavioral",
  },
  {
    term: "Projection Bias",
    story: "While grocery shopping while hungry, Daniel bought much more food than he needed, incorrectly assuming his future self would want as much food as his current hungry self did.",
    explanation: "Projection bias is our tendency to overestimate how much our future preferences will resemble our current preferences, failing to account for how our states and circumstances will change.",
    category: "Decision Making",
    icon: "cognitive",
  }
];
